### ISSUE TITLE
Better handling of abandoned unix socket after error

### ISSUE THREAD

**Issue by caolan** [caolan/mutiny#31]
If mutinyd exits with an exception the unix socket is not removed. This is a bit annoying during development as it requires the manual removal of the socket before mutinyd can be started again.

Would it be a good idea to test if any other processes are using an existing socket on start up and removing it if not?

**Comment by grbgfe** [comment]
I believe this also happens on my system when mutinyd is running in the foreground and I use ctrl-c to kill it. Maybe we should add a catch for that signal and remove the socket file on exit?  

Meanwhile, I will add some logic to remove the socket file on startup when it's not being used.

**Comment by caolan** [comment]
> I believe this also happens on my system when mutinyd is running in the foreground and I use ctrl-c to kill it. Maybe we should add a catch for that signal and remove the socket file on exit?
> 
> Meanwhile, I will add some logic to remove the socket file on startup when it's not being used.

At least on Linux, this signal is caught and the socket removed by mutinyd before it exits. Please could you confirm if that is working or not on macos and raise a ticket if it's not?

**Comment by caolan** [comment]
Closed by #36
